import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google"; //폰트설정
import "./globals.css";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
const geistSans = Geist({ //오브젝트를 인수로 가진 함수
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App:KDT_01",
  description: "Generated by create next app",
};

//중복되는 컴포넌트(고정적으로 보여져야하는것) 칠드런바깥에 써야함. 
export default function RootLayout({ //루트레이아웃이라는 컴포넌트 . 컴포넌트 명과 파일명이 달라도 되는게 노드제이에스의 차이. 컴포넌트는 대문자로 시작해야하므로 대문자로시작, 파일명은 달라도됨.  근데 layout.tsx는 절대 파일명을 다르게 하면안됨. 프레임워크이므로 정해진 규칙틀이 있음. 제일처음에 레이아웃.tsx파일을 보게 되어있는게 넥스트제이에스의 로직이여서. 위치도 바꿔선안되고, 앱폴더의 위치를바꿔도 안됨. 앱라우터를 쓸거임. 리액트가 인덱스.html의 앱컴포넌트를 보듯. 페이지.tsx도 손대면안됨. 
  children, //중요  맨처음 칠드런은 page.tsx을 쓰는거임 .Home()컴포넌트 // 우리의 레이아웃은 전체(네비,메인,푸터)를 브라우저라우츠로 싸고, 바뀌는 부분(메인)을 라우츠로 싸서 라우팅했는데 노드제이에스에선 전체부분은 에이아웃.tsx이고 바뀌는 부분(main)은 칠드런부분임.(page.tsx)
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        <div className='w-full xl:w-8/10 h-screen mx-auto flex flex-col'>
      <header className='w-full h-20 flex justify-center '>
          <Nav/> 
      </header>
      <main className='w-full  flex-grow text-center
      flex flex-col justify-start items-center overflow-y-auto '>  
        {children} 
      </main>
      <Footer/>
    </div>
      </body>
    </html>
  );
}
